

name: Mi Workflow GHA + AWS + role
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Confuguracion de las credenciales de aws
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
            audience: sts.amazonaws.com
            role-to-assume: arn:aws:iam::545009863906:role/roleawsgha
            aws-region: us-east-1

      # - name: Checkout del repositorio
      #   uses: actions/checkout@v6

      # - name: Implementar node
      #   uses: actions/setup-node@v6
      #   with:
      #     node-version: 24

      # - name: Install dependencies
      #   run: npm install

      # - name: Iniciar node
      #   run: npm run dev



      


